# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1uZMA_oqfaPGGeDmBp30hTAO3hnh9l0
"""



import streamlit as st
import pandas as pd
import os

# --- Function to calculate BMI ---
def calculate_bmi(weight, height_cm):
    height_m = height_cm / 100
    bmi = weight / (height_m ** 2)
    return round(bmi, 2)

# --- Function to get BMI category and suggestions ---
def get_bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight", "High-calorie nutritious meals", "Strength training, yoga"
    elif 18.5 <= bmi < 24.9:
        return "Normal", "Balanced meals with carbs, protein, fats", "Regular moderate exercise, walking, cycling"
    elif 25 <= bmi < 29.9:
        return "Overweight", "Low-carb diet with portion control", "Cardio, brisk walking, HIIT"
    else:
        return "Obese", "Calorie-deficit meals, more veggies and proteins", "Low-impact cardio, swimming, walking"

# --- Save data to CSV ---
def save_user_data(data, file='bmi_users.csv'):
    if os.path.exists(file):
        df = pd.read_csv(file)
        df = pd.concat([df, pd.DataFrame([data])], ignore_index=True)
    else:
        df = pd.DataFrame([data])
    df.to_csv(file, index=False)

# --- Streamlit App Layout ---
st.title("🏋️ BMI Calculator & Wellness Assistant")

# Inputs
name = st.text_input("Enter your name")
age = st.number_input("Enter your age", min_value=1)
gender = st.selectbox("Select gender", ["Male", "Female", "Other"])
height = st.number_input("Enter your height (in cm)", min_value=50)
weight = st.number_input("Enter your weight (in kg)", min_value=10)

if st.button("Calculate BMI"):
    bmi = calculate_bmi(weight, height)
    category, meal_plan, exercises = get_bmi_category(bmi)

    st.success(f"{name}, your BMI is **{bmi}** — *{category}*")
    st.markdown(f"**Recommended Meal Plan:** {meal_plan}")
    st.markdown(f"**Suggested Exercises:** {exercises}")

    # Save user data
    user_data = {
        "Name": name,
        "Age": age,
        "Gender": gender,
        "Height_cm": height,
        "Weight_kg": weight,
        "BMI": bmi,
        "Category": category
    }
    save_user_data(user_data)
    st.info("Your data has been saved for future use.")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit pandas